### ISSUE TITLE
students.csv - nome e numero em falta

### ISSUE THREAD

**Issue by Princesacorderosa** [StuntsPT/pr_bio_2019-2020_assignments#55]
Falta o nome e número de estudante no repositorio, para resolve-lo, commit é d73f6e4d9f7b00dcaf045ac1e8f7bbf16e80ab22 .

**Comment by StuntsPT** [comment]
Na verdade não está resolvido.
O teu nome e número não aparecem no ficheiro `students.csv`. O commit d73f6e4 não resolve o issue, muda só um nome de ficheiro. =-(

**Comment by Princesacorderosa** [comment]
Não sei o que fiz de errado, mas voltei a fazer e, what about this 
 d73f6e4d9f7b00dcaf045ac1e8f7bbf16e80ab22 ?

**Comment by StuntsPT** [comment]
Esse commit é o mesmo. O problema é que não chegaste a acrescentar o teu nome e número ao ficheiro `students.csv`.
Este é o teu ficheiro:
https://github.com/Princesacorderosa/pr_bio_2019-2020_assignments/blob/master/students.csv

Como vês, não está lá o teu nome nem número. Basta voltares a clonar o repositório, fazeres a alteração, fazeres *push* para o github e voltares a fazer *pull request* que fica resolvido.

**Comment by Princesacorderosa** [comment]
tenho agora este commit : 2c840c9

**Comment by StuntsPT** [comment]
Excelente! É isso mesmo.
